In [1]:
import pandas as pd
import numpy as np
import datetime as dt

In [99]:
eventsData = pd.read_csv("data/Eventos(+completo).csv",low_memory = False)

In [100]:
eventsData.columns

Index(['Unnamed: 0', 'timestamp', 'event', 'person', 'url', 'sku', 'model',
       'condition', 'storage', 'color', 'skus', 'search_term', 'staticpage',
       'campaign_source', 'search_engine', 'channel', 'new_vs_returning',
       'city', 'region', 'country', 'device_type', 'screen_resolution',
       'operating_system_version', 'browser_version', 'Parte del dia'],
      dtype='object')

In [101]:
eventsData["event"].value_counts()

viewed product       1248124
brand listing         216312
visited site          204069
ad campaign hit       191388
generic listing       160176
searched products     130616
search engine hit     106406
checkout               65315
staticpage             11201
conversion              7091
lead                     983
Name: event, dtype: int64

In [103]:
conversiones = eventsData[eventsData["event"] == "conversion"]

In [104]:
conversiones.head()

,Unnamed: 0,timestamp,event,person,url,sku,model,condition,storage,color,...,channel,new_vs_returning,city,region,country,device_type,screen_resolution,operating_system_version,browser_version,Parte del dia
33,33,2018-05-18 00:29:24,checkout,15ea8012,NaN,12802.0,samsung galaxy s8 plus,Excelente,64GB,Prata,...,NaN,NaN,Itaquaquecetuba,Sao Paulo,Brazil,Smartphone,360x640,Android 7,Chrome Mobile 66.0,Noche
60,60,2018-05-18 00:22:58,checkout,43790d8f,NaN,10378.0,motorola moto g4 plus,Bom,32GB,Bambu,...,NaN,NaN,São Paulo,Sao Paulo,Brazil,Smartphone,360x640,Android 6,Chrome Mobile 66.0,Noche
76,76,2018-05-18 00:38:51,checkout,d614c608,NaN,6343.0,samsung galaxy j5,Bom,16GB,Branco,...,NaN,NaN,São José dos Campos,Sao Paulo,Brazil,Smartphone,360x640,Android 6.0.1,Chrome Mobile 66.0,Noche
133,133,2018-05-18 00:57:32,checkout,55d1e0ee,NaN,6663.0,samsung galaxy core plus duos tv,Excelente,4GB,Preto,...,NaN,NaN,Florianópolis,Santa Catarina,Brazil,Smartphone,360x640,Android 6.0.1,Samsung Internet 6.4,Noche
147,147,2018-05-18 01:12:43,checkout,bb78c182,NaN,7631.0,motorola moto g3 4g,Bom,16GB,Preto,...,NaN,NaN,Ceilandia,Federal District,Brazil,Computer,1920x1080,Windows 10,Chrome 66.0,Madrugada

In [105]:
conversiones["marca"] = conversiones["model"].map(lambda x:"apple" if(x.split(" ")[0] in ["iphone","ipad"]) else x.split(" ")[0])

/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [106]:
conversiones["version"] = conversiones["model"].map(lambda x:" ".join(x.split(" ")[0:2]) if(x.split(" ")[0] in ["iphone","ipad"]) else " ".join(x.split(" ")[1:3]))
conversiones["version"].value_counts()

/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

iphone 6          6988
iphone 6s         5658
iphone 5s         5619
galaxy j5         4246
galaxy j7         3649
galaxy s7         3633
iphone 7          3621
galaxy s6         2921
galaxy s8         2350
moto g4           2035
moto g2           1802
galaxy a5         1657
galaxy s5         1363
galaxy gran       1336
iphone 5c         1223
moto g5           1198
iphone se         1118
moto g3            994
galaxy j2          937
galaxy note        877
galaxy a7          839
iphone 4s          816
iphone 5           804
galaxy j1          787
galaxy win         653
moto x             632
moto z             615
galaxy core        607
moto x2            466
iphone 4g          436
                  ...
ipad air            39
g4 h815p            37
g3 stylus           36
xperia z5           29
k4                  26
k8                  25
g3 beat             21
zenfone 2           20
g4 beat             19
 x                  19
g4 stylus           17
nexus 5             17
go 4g               16
ipad 3              15
zenfone 5           14
x power             13
ipad 4              13
ipad 2              12
you                 10
zenfone 6           10
gear s2              7
galaxy young         6
muv                  6
zenfone go           3
gear fit             2
zenfone selfie       2
muv pro              1
gear s3              1
galaxy mega          1
l80 dual             1
Name: version, dtype: int64

In [9]:
conversiones.head()

,Unnamed: 0,timestamp,event,person,url,sku,model,condition,storage,color,...,city,region,country,device_type,screen_resolution,operating_system_version,browser_version,Parte del dia,marca,version
195,195,2018-05-18 01:12:20,conversion,49c19e32,NaN,2683.0,iphone 5c,Bom,16GB,Rosa,...,São Paulo,Sao Paulo,Brazil,Smartphone,360x640,Android 6.0.1,Chrome Mobile 66.0,Madrugada,apple,iphone 5c
234,234,2018-05-18 01:05:23,conversion,49c19e32,NaN,2683.0,iphone 5c,Bom,16GB,Rosa,...,São Paulo,Sao Paulo,Brazil,Smartphone,360x640,Android 6.0.1,Chrome Mobile 66.0,Madrugada,apple,iphone 5c
724,724,2018-05-29 07:51:14,conversion,39df97e0,NaN,9358.0,samsung galaxy j2 prime tv,Excelente,8GB,Rosa,...,Juiz de Fora,Minas Gerais,Brazil,Smartphone,360x640,Android 7.1.1,Chrome Mobile 64.0,Mañana,samsung,galaxy j2
744,744,2018-05-29 07:13:30,conversion,380c0e60,NaN,6314.0,samsung galaxy note 5,Muito Bom,32GB,Preto,...,São Paulo,Sao Paulo,Brazil,Smartphone,320x480,Android 4.4.4,Facebook 94,Mañana,samsung,galaxy note
1198,1198,2018-05-29 19:31:46,conversion,35ee0cc8,NaN,10924.0,samsung galaxy a5 2017,Bom,32GB,Dourado,...,Unknown,Unknown,Unknown,Smartphone,360x640,Android 6.0.1,Chrome Mobile 66.0,Noche,samsung,galaxy a5

In [10]:
conversiones = conversiones[["person","timestamp","marca","model"]]

In [11]:
conversiones.head()

        person            timestamp    marca                       model
195   49c19e32  2018-05-18 01:12:20    apple                   iphone 5c
234   49c19e32  2018-05-18 01:05:23    apple                   iphone 5c
724   39df97e0  2018-05-29 07:51:14  samsung  samsung galaxy j2 prime tv
744   380c0e60  2018-05-29 07:13:30  samsung       samsung galaxy note 5
1198  35ee0cc8  2018-05-29 19:31:46  samsung      samsung galaxy a5 2017

In [12]:
marcas = conversiones["marca"].value_counts()

In [13]:
marcas

samsung     3615
apple       2031
motorola    1104
lg           161
lenovo        99
sony          56
asus          22
quantum        3
Name: marca, dtype: int64

In [14]:
prob_marcas = marcas/conversiones["person"].count()

In [15]:
prob_marcas

samsung     0.509801
apple       0.286419
motorola    0.155690
lg          0.022705
lenovo      0.013961
sony        0.007897
asus        0.003103
quantum     0.000423
Name: marca, dtype: float64

In [16]:
modelos = conversiones["model"].value_counts()

In [17]:
prob_model = modelos/conversiones["person"].count()

In [18]:
prob_model.head()

samsung galaxy j5           0.073191
iphone 5s                   0.069948
iphone 6                    0.056127
iphone 6s                   0.043294
motorola moto g2 3g dual    0.038358
Name: model, dtype: float64

In [19]:
conversiones.head()

        person            timestamp    marca                       model
195   49c19e32  2018-05-18 01:12:20    apple                   iphone 5c
234   49c19e32  2018-05-18 01:05:23    apple                   iphone 5c
724   39df97e0  2018-05-29 07:51:14  samsung  samsung galaxy j2 prime tv
744   380c0e60  2018-05-29 07:13:30  samsung       samsung galaxy note 5
1198  35ee0cc8  2018-05-29 19:31:46  samsung      samsung galaxy a5 2017

In [20]:
def datetime(date,format_string):
    return pd.to_datetime(date,format= format_string,errors='coerce')

eventsData["timestamp"]= datetime(eventsData["timestamp"],"%Y-%m-%dT%H:%M:%S")

In [21]:
eventsData["month"] = eventsData["timestamp"].map(lambda x: x.month)
eventsData["day"] = eventsData["timestamp"].map(lambda x: x.day)

In [22]:
eventsData.head()

,Unnamed: 0,timestamp,event,person,url,sku,model,condition,storage,color,...,city,region,country,device_type,screen_resolution,operating_system_version,browser_version,Parte del dia,month,day
0,0,2018-05-18 00:11:59,viewed product,4886f805,NaN,9288.0,samsung galaxy j7 prime,Excelente,32GB,Dourado,...,Cantagalo,Rio de Janeiro,Brazil,Smartphone,360x640,Android 7,Chrome Mobile 64.0,Noche,5,18
1,1,2018-05-18 00:11:27,viewed product,ad93850f,NaN,304.0,iphone 5s,Muito Bom,32GB,Cinza espacial,...,São Paulo,Sao Paulo,Brazil,Smartphone,360x640,Android 5.1.1,Chrome Mobile 66.0,Noche,5,18
2,2,2018-05-18 00:11:16,viewed product,0297fc1e,NaN,6888.0,iphone 6s,Muito Bom,64GB,Prateado,...,Niterói,Rio de Janeiro,Brazil,Smartphone,360x640,Android 6.0.1,Chrome Mobile 61.0,Noche,5,18
3,3,2018-05-18 00:11:14,viewed product,2d681dd8,NaN,11890.0,iphone 7,Bom,128GB,Vermelho,...,Juquitiba,Sao Paulo,Brazil,Computer,1360x768,Windows 8.1,Chrome 66.0,Noche,5,18
4,4,2018-05-18 00:11:09,viewed product,cccea85e,NaN,7517.0,lg g4 h818p,Excelente,32GB,Branco,...,Osasco,Sao Paulo,Brazil,Computer,1536x864,Windows 7,Chrome 66.0,Noche,5,18

In [58]:
last_15 = eventsData

In [59]:
last_15.head()

,Unnamed: 0,timestamp,event,person,url,sku,model,condition,storage,color,...,city,region,country,device_type,screen_resolution,operating_system_version,browser_version,Parte del dia,month,day
0,0,2018-05-18 00:11:59,viewed product,4886f805,NaN,9288.0,samsung galaxy j7 prime,Excelente,32GB,Dourado,...,Cantagalo,Rio de Janeiro,Brazil,Smartphone,360x640,Android 7,Chrome Mobile 64.0,Noche,5,18
1,1,2018-05-18 00:11:27,viewed product,ad93850f,NaN,304.0,iphone 5s,Muito Bom,32GB,Cinza espacial,...,São Paulo,Sao Paulo,Brazil,Smartphone,360x640,Android 5.1.1,Chrome Mobile 66.0,Noche,5,18
2,2,2018-05-18 00:11:16,viewed product,0297fc1e,NaN,6888.0,iphone 6s,Muito Bom,64GB,Prateado,...,Niterói,Rio de Janeiro,Brazil,Smartphone,360x640,Android 6.0.1,Chrome Mobile 61.0,Noche,5,18
3,3,2018-05-18 00:11:14,viewed product,2d681dd8,NaN,11890.0,iphone 7,Bom,128GB,Vermelho,...,Juquitiba,Sao Paulo,Brazil,Computer,1360x768,Windows 8.1,Chrome 66.0,Noche,5,18
4,4,2018-05-18 00:11:09,viewed product,cccea85e,NaN,7517.0,lg g4 h818p,Excelente,32GB,Branco,...,Osasco,Sao Paulo,Brazil,Computer,1536x864,Windows 7,Chrome 66.0,Noche,5,18

In [60]:
last_15 = last_15[last_15["event"] == "checkout"]

In [61]:
last_15 = last_15[last_15["month"] == 5]

In [62]:
last_15 = last_15[last_15["day"] >14]

In [63]:
last_15_product = last_15[["person","model"]]

In [64]:
last_15_product.head()

       person                             model
33   15ea8012            samsung galaxy s8 plus
60   43790d8f             motorola moto g4 plus
76   d614c608                 samsung galaxy j5
133  55d1e0ee  samsung galaxy core plus duos tv
147  bb78c182               motorola moto g3 4g

In [65]:
last_15_product = last_15_product.dropna()

In [66]:
last_15_product["marca"] = last_15_product["model"].map(lambda x:"apple" if(x.split(" ")[0] in ["iphone","ipad"]) else x.split(" ")[0])

In [67]:
last_15_product["version"] = last_15_product["model"].map(lambda x:" ".join(x.split(" ")[0:2]) if(x.split(" ")[0] in ["iphone","ipad"]) else " ".join(x.split(" ")[1:3]))

In [68]:
last_15_product.head()

       person                             model     marca      version
33   15ea8012            samsung galaxy s8 plus   samsung    galaxy s8
60   43790d8f             motorola moto g4 plus  motorola      moto g4
76   d614c608                 samsung galaxy j5   samsung    galaxy j5
133  55d1e0ee  samsung galaxy core plus duos tv   samsung  galaxy core
147  bb78c182               motorola moto g3 4g  motorola      moto g3

In [69]:
last_15_product = last_15_product.drop("model",axis=1)

In [70]:
"samsung" in prob_marcas.keys()

True

In [71]:
last_15_product["prob_marca_checkout"] = last_15_product["marca"].map(lambda x:prob_marcas[x] if(x in prob_marcas.keys()) else 0)

In [72]:
last_15_product["prob_model_checkout"] = last_15_product["version"].map(lambda x:prob_model[x] if(x in prob_model.keys()) else 0)

In [73]:
last_15_product.head()

       person     marca      version  prob_marca_checkout  prob_model_checkout
33   15ea8012   samsung    galaxy s8             0.509801                  0.0
60   43790d8f  motorola      moto g4             0.155690                  0.0
76   d614c608   samsung    galaxy j5             0.509801                  0.0
133  55d1e0ee   samsung  galaxy core             0.509801                  0.0
147  bb78c182  motorola      moto g3             0.155690                  0.0

In [74]:
last_15_product = last_15_product[["person","prob_marca_checkout","prob_model_checkout"]]

In [75]:
last_15_product.head()

       person  prob_marca_checkout  prob_model_checkout
33   15ea8012             0.509801                  0.0
60   43790d8f             0.155690                  0.0
76   d614c608             0.509801                  0.0
133  55d1e0ee             0.509801                  0.0
147  bb78c182             0.155690                  0.0

In [76]:
last_15_product["prob_marca_checkout"].value_counts()

0.509801    21499
0.286419    20051
0.155690     6728
0.022705      945
0.013961      451
0.007897      339
0.003103       49
0.000423       30
Name: prob_marca_checkout, dtype: int64

In [77]:
last_15_product["cant_conversiones"] = 1

In [78]:
last_15_product = last_15_product.groupby("person",as_index = False).sum()

In [79]:
last_15_product.head()

     person  prob_marca_checkout  prob_model_checkout  cant_conversiones
0  0008ed71             0.818925             0.010436                  3
1  00091926             0.572839             0.086589                  2
2  000ba417             2.704696             0.000000                  6
3  000c79fe             0.286419             0.012269                  1
4  000e4d9e             0.509801             0.000000                  1

In [80]:
last_15_product["prob_marca_checkout"] = last_15_product["prob_marca_checkout"] / (last_15_product["cant_conversiones"]+1)

In [81]:
last_15_product.head()

     person  prob_marca_checkout  prob_model_checkout  cant_conversiones
0  0008ed71             0.204731             0.010436                  3
1  00091926             0.190946             0.086589                  2
2  000ba417             0.386385             0.000000                  6
3  000c79fe             0.143210             0.012269                  1
4  000e4d9e             0.254901             0.000000                  1

In [82]:
last_15_product = last_15_product[["person","prob_marca_checkout"]]

In [83]:
last_15_product.head()

     person  prob_marca_checkout
0  0008ed71             0.204731
1  00091926             0.190946
2  000ba417             0.386385
3  000c79fe             0.143210
4  000e4d9e             0.254901

In [84]:
usersDataTrain = pd.read_csv("setEntrenamiento.csv")

In [85]:
usersDataTrain.head()

,person,cant_seciones,event_checkout,event_conversion,event_ad campaign hit,event_lead,skus,Busca_terminos_populares,Computer,Smartphone,...,cantidadDeStaticPage,sku_multiple,count_activity_last_month,conversiones_lastmonth,checkout_lastmonth,viewed_lastmonth,label,kmean,prob_marca,prob_model
0,0008ed71,3,3.0,0.0,0.0,0.0,1,0,1.0,0.0,...,0.0,12.0,6.0,0.0,3.0,0.0,0,0,0.204731,0.002609
1,000c79fe,1,1.0,0.0,1.0,0.0,1,8,0.0,1.0,...,0.0,79.0,17.0,0.0,1.0,3.0,0,0,0.229136,0.009815
2,001802e4,1,1.0,0.0,5.0,0.0,1,0,0.0,1.0,...,0.0,24.0,19.0,0.0,1.0,4.0,0,0,0.250617,0.030126
3,0019e639,21,15.0,2.0,29.0,0.0,1,3,1.0,0.0,...,0.0,608.0,359.0,1.0,6.0,161.0,0,2,0.200583,0.000000
4,001b0bf9,1,2.0,1.0,0.0,0.0,1,0,0.0,0.0,...,0.0,24.0,7.0,1.0,2.0,2.0,0,3,0.424834,0.000000

In [86]:
usersDataTrain = pd.merge(usersDataTrain,last_15_product,how = "left",on = "person")

In [87]:
usersDataTrain["prob_marca_checkout"] = usersDataTrain["prob_marca"].fillna(0)

In [90]:
usersDataTrain.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19414 entries, 0 to 19413
Data columns (total 77 columns):
person                               19414 non-null object
cant_seciones                        19414 non-null int64
event_checkout                       19414 non-null float64
event_conversion                     19414 non-null float64
event_ad campaign hit                19414 non-null float64
event_lead                           19414 non-null float64
skus                                 19414 non-null int64
Busca_terminos_populares             19414 non-null int64
Computer                             19414 non-null float64
Smartphone                           19414 non-null float64
otros                                19414 non-null float64
marca_apple                          19414 non-null float64
marca_asus                           19414 non-null float64
marca_lenovo                         19414 non-null float64
marca_lg                             19414 non-null float64
marca_motorola                       19414 non-null float64
marca_samsung                        19414 non-null float64
marca_sony                           19414 non-null float64
condition_Bom                        19414 non-null float64
condition_Bom - Sem Touch ID         19414 non-null float64
condition_Excelente                  19414 non-null float64
condition_Muito Bom                  19414 non-null float64
version_galaxy j7                    19414 non-null float64
version_galaxy j5                    19414 non-null float64
version_galaxy s7                    19414 non-null float64
version_iphone 6                     19414 non-null float64
version_iphone 5s                    19414 non-null float64
version_iphone 6s                    19414 non-null float64
version_moto g4                      19414 non-null float64
version_moto g2                      19414 non-null float64
version_galaxy s6                    19414 non-null float64
storage_128GB                        19414 non-null float64
storage_16GB                         19414 non-null float64
storage_256GB                        19414 non-null float64
storage_32GB                         19414 non-null float64
storage_4GB                          19414 non-null float64
storage_512MB                        19414 non-null float64
storage_64GB                         19414 non-null float64
storage_8GB                          19414 non-null float64
Parte del dia_Madrugada              19414 non-null float64
Parte del dia_Mañana                 19414 non-null float64
Parte del dia_Noche                  19414 non-null float64
Parte del dia_Tarde                  19414 non-null float64
campaign_source_google               19414 non-null float64
campaign_source_criteo               19414 non-null float64
campaign_source_rtbhouse             19414 non-null float64
channel_Direct                       19414 non-null float64
channel_Paid                         19414 non-null float64
channel_Organic                      19414 non-null float64
channel_Referral                     19414 non-null float64
Brasilero                            19414 non-null float64
ventas_region                        19414 non-null float64
count_activity                       19414 non-null float64
conversiones_15lastdays              19414 non-null float64
checkout_15lastdays                  19414 non-null float64
viewed_15lastday                     19414 non-null float64
color_Preto                          19414 non-null float64
color_Dourado                        19414 non-null float64
color_Branco                         19414 non-null float64
color_Cinza espacial                 19414 non-null float64
new_15lastdays                       19414 non-null float64
sku                                  19414 non-null float64
cantidad_De_Compras_De_Mismo_Sku     19414 non-null float64
Cantidad_De_Busquedas_Por_Termino    19414 non-null float64
search_and_purchase                  19414 non-null float64
cantidad_de_Url_de_compra            19414 non-null float64
cantidadDeStaticPage                 19414 non-null float64
sku_multiple                         19414 non-null float64
count_activity_last_month            19414 non-null float64
conversiones_lastmonth               19414 non-null float64
checkout_lastmonth                   19414 non-null float64
viewed_lastmonth                     19414 non-null float64
label                                19414 non-null int64
kmean                                19414 non-null int64
prob_marca                           19414 non-null float64
prob_model                           19414 non-null float64
prob_marca_checkout                  19414 non-null float64
dtypes: float64(71), int64(5), object(1)
memory usage: 11.6+ MB

In [91]:
usersDataTrain.to_csv("setEntrenamiento.csv",index = False)

In [92]:
test = pd.read_csv('setTest.csv')

In [93]:
test.head()

,person,cant_seciones,event_checkout,event_conversion,event_ad campaign hit,event_lead,skus,Busca_terminos_populares,Computer,Smartphone,...,cantidad_de_Url_de_compra,cantidadDeStaticPage,sku_multiple,count_activity_last_month,conversiones_lastmonth,checkout_lastmonth,viewed_lastmonth,kmean,prob_marca,prob_model
0,4886f805,1,1.0,0.0,0.0,0.0,1,0,0.0,1.0,...,0.0,0.0,21.0,9.0,0.0,1.0,4.0,0,0.424834,0.000000
1,0297fc1e,96,7.0,0.0,29.0,1.0,1,5,0.0,1.0,...,29.0,0.0,326.0,312.0,0.0,2.0,233.0,0,0.283584,0.041827
2,2d681dd8,2,1.0,0.0,1.0,0.0,1,1,1.0,0.0,...,1.0,0.0,53.0,26.0,0.0,1.0,13.0,0,0.197603,0.004908
3,cccea85e,28,1.0,0.0,15.0,0.0,1,0,1.0,0.0,...,15.0,5.0,240.0,836.0,0.0,1.0,739.0,5,0.126065,0.000434
4,4c8a8b93,20,2.0,0.0,14.0,0.0,1,9,0.0,1.0,...,14.0,0.0,132.0,257.0,0.0,2.0,177.0,0,0.288460,0.042187

In [94]:
test = pd.merge(test,last_15_product,on="person",how="left")

In [95]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19415 entries, 0 to 19414
Data columns (total 76 columns):
person                               19415 non-null object
cant_seciones                        19415 non-null int64
event_checkout                       19415 non-null float64
event_conversion                     19415 non-null float64
event_ad campaign hit                19415 non-null float64
event_lead                           19415 non-null float64
skus                                 19415 non-null int64
Busca_terminos_populares             19415 non-null int64
Computer                             19415 non-null float64
Smartphone                           19415 non-null float64
otros                                19415 non-null float64
marca_apple                          19415 non-null float64
marca_asus                           19415 non-null float64
marca_lenovo                         19415 non-null float64
marca_lg                             19415 non-null float64
marca_motorola                       19415 non-null float64
marca_samsung                        19415 non-null float64
marca_sony                           19415 non-null float64
condition_Bom                        19415 non-null float64
condition_Bom - Sem Touch ID         19415 non-null float64
condition_Excelente                  19415 non-null float64
condition_Muito Bom                  19415 non-null float64
version_galaxy j7                    19415 non-null float64
version_galaxy j5                    19415 non-null float64
version_galaxy s7                    19415 non-null float64
version_iphone 6                     19415 non-null float64
version_iphone 5s                    19415 non-null float64
version_iphone 6s                    19415 non-null float64
version_moto g4                      19415 non-null float64
version_moto g2                      19415 non-null float64
version_galaxy s6                    19415 non-null float64
storage_128GB                        19415 non-null float64
storage_16GB                         19415 non-null float64
storage_256GB                        19415 non-null float64
storage_32GB                         19415 non-null float64
storage_4GB                          19415 non-null float64
storage_512MB                        19415 non-null float64
storage_64GB                         19415 non-null float64
storage_8GB                          19415 non-null float64
Parte del dia_Madrugada              19415 non-null float64
Parte del dia_Mañana                 19415 non-null float64
Parte del dia_Noche                  19415 non-null float64
Parte del dia_Tarde                  19415 non-null float64
campaign_source_google               19415 non-null float64
campaign_source_criteo               19415 non-null float64
campaign_source_rtbhouse             19415 non-null float64
channel_Direct                       19415 non-null float64
channel_Paid                         19415 non-null float64
channel_Organic                      19415 non-null float64
channel_Referral                     19415 non-null float64
Brasilero                            19415 non-null float64
ventas_region                        19415 non-null float64
count_activity                       19415 non-null float64
conversiones_15lastdays              19415 non-null float64
checkout_15lastdays                  19415 non-null float64
viewed_15lastday                     19415 non-null float64
color_Preto                          19415 non-null float64
color_Dourado                        19415 non-null float64
color_Branco                         19415 non-null float64
color_Cinza espacial                 19415 non-null float64
new_15lastdays                       19415 non-null float64
sku                                  19415 non-null float64
cantidad_De_Compras_De_Mismo_Sku     19415 non-null float64
Cantidad_De_Busquedas_Por_Termino    19415 non-null float64
search_and_purchase                  19415 non-null float64
cantidad_de_Url_de_compra            19415 non-null float64
cantidadDeStaticPage                 19415 non-null float64
sku_multiple                         19415 non-null float64
count_activity_last_month            19415 non-null float64
conversiones_lastmonth               19415 non-null float64
checkout_lastmonth                   19415 non-null float64
viewed_lastmonth                     19415 non-null float64
kmean                                19415 non-null int64
prob_marca                           19415 non-null float64
prob_model                           19415 non-null float64
prob_marca_checkout                  15643 non-null float64
dtypes: float64(71), int64(4), object(1)
memory usage: 11.4+ MB

In [96]:

test["prob_marca_checkout"] = test["prob_model"].fillna(0)

In [97]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19415 entries, 0 to 19414
Data columns (total 76 columns):
person                               19415 non-null object
cant_seciones                        19415 non-null int64
event_checkout                       19415 non-null float64
event_conversion                     19415 non-null float64
event_ad campaign hit                19415 non-null float64
event_lead                           19415 non-null float64
skus                                 19415 non-null int64
Busca_terminos_populares             19415 non-null int64
Computer                             19415 non-null float64
Smartphone                           19415 non-null float64
otros                                19415 non-null float64
marca_apple                          19415 non-null float64
marca_asus                           19415 non-null float64
marca_lenovo                         19415 non-null float64
marca_lg                             19415 non-null float64
marca_motorola                       19415 non-null float64
marca_samsung                        19415 non-null float64
marca_sony                           19415 non-null float64
condition_Bom                        19415 non-null float64
condition_Bom - Sem Touch ID         19415 non-null float64
condition_Excelente                  19415 non-null float64
condition_Muito Bom                  19415 non-null float64
version_galaxy j7                    19415 non-null float64
version_galaxy j5                    19415 non-null float64
version_galaxy s7                    19415 non-null float64
version_iphone 6                     19415 non-null float64
version_iphone 5s                    19415 non-null float64
version_iphone 6s                    19415 non-null float64
version_moto g4                      19415 non-null float64
version_moto g2                      19415 non-null float64
version_galaxy s6                    19415 non-null float64
storage_128GB                        19415 non-null float64
storage_16GB                         19415 non-null float64
storage_256GB                        19415 non-null float64
storage_32GB                         19415 non-null float64
storage_4GB                          19415 non-null float64
storage_512MB                        19415 non-null float64
storage_64GB                         19415 non-null float64
storage_8GB                          19415 non-null float64
Parte del dia_Madrugada              19415 non-null float64
Parte del dia_Mañana                 19415 non-null float64
Parte del dia_Noche                  19415 non-null float64
Parte del dia_Tarde                  19415 non-null float64
campaign_source_google               19415 non-null float64
campaign_source_criteo               19415 non-null float64
campaign_source_rtbhouse             19415 non-null float64
channel_Direct                       19415 non-null float64
channel_Paid                         19415 non-null float64
channel_Organic                      19415 non-null float64
channel_Referral                     19415 non-null float64
Brasilero                            19415 non-null float64
ventas_region                        19415 non-null float64
count_activity                       19415 non-null float64
conversiones_15lastdays              19415 non-null float64
checkout_15lastdays                  19415 non-null float64
viewed_15lastday                     19415 non-null float64
color_Preto                          19415 non-null float64
color_Dourado                        19415 non-null float64
color_Branco                         19415 non-null float64
color_Cinza espacial                 19415 non-null float64
new_15lastdays                       19415 non-null float64
sku                                  19415 non-null float64
cantidad_De_Compras_De_Mismo_Sku     19415 non-null float64
Cantidad_De_Busquedas_Por_Termino    19415 non-null float64
search_and_purchase                  19415 non-null float64
cantidad_de_Url_de_compra            19415 non-null float64
cantidadDeStaticPage                 19415 non-null float64
sku_multiple                         19415 non-null float64
count_activity_last_month            19415 non-null float64
conversiones_lastmonth               19415 non-null float64
checkout_lastmonth                   19415 non-null float64
viewed_lastmonth                     19415 non-null float64
kmean                                19415 non-null int64
prob_marca                           19415 non-null float64
prob_model                           19415 non-null float64
prob_marca_checkout                  19415 non-null float64
dtypes: float64(71), int64(4), object(1)
memory usage: 11.4+ MB

In [98]:
test.to_csv('setTest.csv',index = False)