In [1]:
import pandas as pd
import numpy as np
import datetime as dt

In [2]:
eventsData = pd.read_csv("data/Eventos(+completo).csv",low_memory = False)

In [3]:
eventsData.columns

Index(['Unnamed: 0', 'timestamp', 'event', 'person', 'url', 'sku', 'model',
       'condition', 'storage', 'color', 'skus', 'search_term', 'staticpage',
       'campaign_source', 'search_engine', 'channel', 'new_vs_returning',
       'city', 'region', 'country', 'device_type', 'screen_resolution',
       'operating_system_version', 'browser_version', 'Parte del dia'],
      dtype='object')

In [4]:
eventsData["event"].value_counts()

viewed product       1248124
brand listing         216312
visited site          204069
ad campaign hit       191388
generic listing       160176
searched products     130616
search engine hit     106406
checkout               65315
staticpage             11201
conversion              7091
lead                     983
Name: event, dtype: int64

In [5]:
checkout = eventsData[eventsData["event"] == "checkout"]

In [6]:
checkout.head()

,Unnamed: 0,timestamp,event,person,url,sku,model,condition,storage,color,...,channel,new_vs_returning,city,region,country,device_type,screen_resolution,operating_system_version,browser_version,Parte del dia
33,33,2018-05-18 00:29:24,checkout,15ea8012,NaN,12802.0,samsung galaxy s8 plus,Excelente,64GB,Prata,...,NaN,NaN,Itaquaquecetuba,Sao Paulo,Brazil,Smartphone,360x640,Android 7,Chrome Mobile 66.0,Noche
60,60,2018-05-18 00:22:58,checkout,43790d8f,NaN,10378.0,motorola moto g4 plus,Bom,32GB,Bambu,...,NaN,NaN,São Paulo,Sao Paulo,Brazil,Smartphone,360x640,Android 6,Chrome Mobile 66.0,Noche
76,76,2018-05-18 00:38:51,checkout,d614c608,NaN,6343.0,samsung galaxy j5,Bom,16GB,Branco,...,NaN,NaN,São José dos Campos,Sao Paulo,Brazil,Smartphone,360x640,Android 6.0.1,Chrome Mobile 66.0,Noche
133,133,2018-05-18 00:57:32,checkout,55d1e0ee,NaN,6663.0,samsung galaxy core plus duos tv,Excelente,4GB,Preto,...,NaN,NaN,Florianópolis,Santa Catarina,Brazil,Smartphone,360x640,Android 6.0.1,Samsung Internet 6.4,Noche
147,147,2018-05-18 01:12:43,checkout,bb78c182,NaN,7631.0,motorola moto g3 4g,Bom,16GB,Preto,...,NaN,NaN,Ceilandia,Federal District,Brazil,Computer,1920x1080,Windows 10,Chrome 66.0,Madrugada

In [7]:
checkout["marca"] = checkout["model"].map(lambda x:"apple" if(x.split(" ")[0] in ["iphone","ipad"]) else x.split(" ")[0])

/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [8]:
checkout["version"] = checkout["model"].map(lambda x:" ".join(x.split(" ")[0:2]) if(x.split(" ")[0] in ["iphone","ipad"]) else " ".join(x.split(" ")[1:3]))
checkout["version"].value_counts()

/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

iphone 6          6988
iphone 6s         5658
iphone 5s         5619
galaxy j5         4246
galaxy j7         3649
galaxy s7         3633
iphone 7          3621
galaxy s6         2921
galaxy s8         2350
moto g4           2035
moto g2           1802
galaxy a5         1657
galaxy s5         1363
galaxy gran       1336
iphone 5c         1223
moto g5           1198
iphone se         1118
moto g3            994
galaxy j2          937
galaxy note        877
galaxy a7          839
iphone 4s          816
iphone 5           804
galaxy j1          787
galaxy win         653
moto x             632
moto z             615
galaxy core        607
moto x2            466
iphone 4g          436
                  ...
ipad air            39
g4 h815p            37
g3 stylus           36
xperia z5           29
k4                  26
k8                  25
g3 beat             21
zenfone 2           20
g4 beat             19
 x                  19
nexus 5             17
g4 stylus           17
go 4g               16
ipad 3              15
zenfone 5           14
ipad 4              13
x power             13
ipad 2              12
zenfone 6           10
you                 10
gear s2              7
galaxy young         6
muv                  6
zenfone go           3
gear fit             2
zenfone selfie       2
gear s3              1
l80 dual             1
galaxy mega          1
muv pro              1
Name: version, dtype: int64

In [9]:
checkout.head()

,Unnamed: 0,timestamp,event,person,url,sku,model,condition,storage,color,...,city,region,country,device_type,screen_resolution,operating_system_version,browser_version,Parte del dia,marca,version
33,33,2018-05-18 00:29:24,checkout,15ea8012,NaN,12802.0,samsung galaxy s8 plus,Excelente,64GB,Prata,...,Itaquaquecetuba,Sao Paulo,Brazil,Smartphone,360x640,Android 7,Chrome Mobile 66.0,Noche,samsung,galaxy s8
60,60,2018-05-18 00:22:58,checkout,43790d8f,NaN,10378.0,motorola moto g4 plus,Bom,32GB,Bambu,...,São Paulo,Sao Paulo,Brazil,Smartphone,360x640,Android 6,Chrome Mobile 66.0,Noche,motorola,moto g4
76,76,2018-05-18 00:38:51,checkout,d614c608,NaN,6343.0,samsung galaxy j5,Bom,16GB,Branco,...,São José dos Campos,Sao Paulo,Brazil,Smartphone,360x640,Android 6.0.1,Chrome Mobile 66.0,Noche,samsung,galaxy j5
133,133,2018-05-18 00:57:32,checkout,55d1e0ee,NaN,6663.0,samsung galaxy core plus duos tv,Excelente,4GB,Preto,...,Florianópolis,Santa Catarina,Brazil,Smartphone,360x640,Android 6.0.1,Samsung Internet 6.4,Noche,samsung,galaxy core
147,147,2018-05-18 01:12:43,checkout,bb78c182,NaN,7631.0,motorola moto g3 4g,Bom,16GB,Preto,...,Ceilandia,Federal District,Brazil,Computer,1920x1080,Windows 10,Chrome 66.0,Madrugada,motorola,moto g3

In [10]:
checkout = checkout[["person","timestamp","marca","model"]]

In [12]:
checkout.head()

       person            timestamp     marca                             model
33   15ea8012  2018-05-18 00:29:24   samsung            samsung galaxy s8 plus
60   43790d8f  2018-05-18 00:22:58  motorola             motorola moto g4 plus
76   d614c608  2018-05-18 00:38:51   samsung                 samsung galaxy j5
133  55d1e0ee  2018-05-18 00:57:32   samsung  samsung galaxy core plus duos tv
147  bb78c182  2018-05-18 01:12:43  motorola               motorola moto g3 4g

In [13]:
marcas = checkout["marca"].value_counts()

In [14]:
marcas

samsung     27838
apple       26771
motorola     8442
lg           1140
lenovo        573
sony          416
asus          102
quantum        33
Name: marca, dtype: int64

In [15]:
prob_marcas = marcas/checkout["person"].count()

In [16]:
prob_marcas

samsung     0.426211
apple       0.409875
motorola    0.129251
lg          0.017454
lenovo      0.008773
sony        0.006369
asus        0.001562
quantum     0.000505
Name: marca, dtype: float64

In [17]:
modelos = checkout["model"].value_counts()

In [18]:
prob_model = modelos/checkout["person"].count()

In [19]:
prob_model.head()

iphone 6             0.086902
iphone 5s            0.086029
iphone 6s            0.069157
samsung galaxy j5    0.053433
samsung galaxy s7    0.031953
Name: model, dtype: float64

In [20]:
checkout.head()

       person            timestamp     marca                             model
33   15ea8012  2018-05-18 00:29:24   samsung            samsung galaxy s8 plus
60   43790d8f  2018-05-18 00:22:58  motorola             motorola moto g4 plus
76   d614c608  2018-05-18 00:38:51   samsung                 samsung galaxy j5
133  55d1e0ee  2018-05-18 00:57:32   samsung  samsung galaxy core plus duos tv
147  bb78c182  2018-05-18 01:12:43  motorola               motorola moto g3 4g

In [21]:
def datetime(date,format_string):
    return pd.to_datetime(date,format= format_string,errors='coerce')

eventsData["timestamp"]= datetime(eventsData["timestamp"],"%Y-%m-%dT%H:%M:%S")

In [22]:
eventsData["month"] = eventsData["timestamp"].map(lambda x: x.month)
eventsData["day"] = eventsData["timestamp"].map(lambda x: x.day)

In [23]:
eventsData.head()

,Unnamed: 0,timestamp,event,person,url,sku,model,condition,storage,color,...,city,region,country,device_type,screen_resolution,operating_system_version,browser_version,Parte del dia,month,day
0,0,2018-05-18 00:11:59,viewed product,4886f805,NaN,9288.0,samsung galaxy j7 prime,Excelente,32GB,Dourado,...,Cantagalo,Rio de Janeiro,Brazil,Smartphone,360x640,Android 7,Chrome Mobile 64.0,Noche,5,18
1,1,2018-05-18 00:11:27,viewed product,ad93850f,NaN,304.0,iphone 5s,Muito Bom,32GB,Cinza espacial,...,São Paulo,Sao Paulo,Brazil,Smartphone,360x640,Android 5.1.1,Chrome Mobile 66.0,Noche,5,18
2,2,2018-05-18 00:11:16,viewed product,0297fc1e,NaN,6888.0,iphone 6s,Muito Bom,64GB,Prateado,...,Niterói,Rio de Janeiro,Brazil,Smartphone,360x640,Android 6.0.1,Chrome Mobile 61.0,Noche,5,18
3,3,2018-05-18 00:11:14,viewed product,2d681dd8,NaN,11890.0,iphone 7,Bom,128GB,Vermelho,...,Juquitiba,Sao Paulo,Brazil,Computer,1360x768,Windows 8.1,Chrome 66.0,Noche,5,18
4,4,2018-05-18 00:11:09,viewed product,cccea85e,NaN,7517.0,lg g4 h818p,Excelente,32GB,Branco,...,Osasco,Sao Paulo,Brazil,Computer,1536x864,Windows 7,Chrome 66.0,Noche,5,18

In [55]:
last_15 = eventsData

In [56]:
last_15.head()

,Unnamed: 0,timestamp,event,person,url,sku,model,condition,storage,color,...,city,region,country,device_type,screen_resolution,operating_system_version,browser_version,Parte del dia,month,day
0,0,2018-05-18 00:11:59,viewed product,4886f805,NaN,9288.0,samsung galaxy j7 prime,Excelente,32GB,Dourado,...,Cantagalo,Rio de Janeiro,Brazil,Smartphone,360x640,Android 7,Chrome Mobile 64.0,Noche,5,18
1,1,2018-05-18 00:11:27,viewed product,ad93850f,NaN,304.0,iphone 5s,Muito Bom,32GB,Cinza espacial,...,São Paulo,Sao Paulo,Brazil,Smartphone,360x640,Android 5.1.1,Chrome Mobile 66.0,Noche,5,18
2,2,2018-05-18 00:11:16,viewed product,0297fc1e,NaN,6888.0,iphone 6s,Muito Bom,64GB,Prateado,...,Niterói,Rio de Janeiro,Brazil,Smartphone,360x640,Android 6.0.1,Chrome Mobile 61.0,Noche,5,18
3,3,2018-05-18 00:11:14,viewed product,2d681dd8,NaN,11890.0,iphone 7,Bom,128GB,Vermelho,...,Juquitiba,Sao Paulo,Brazil,Computer,1360x768,Windows 8.1,Chrome 66.0,Noche,5,18
4,4,2018-05-18 00:11:09,viewed product,cccea85e,NaN,7517.0,lg g4 h818p,Excelente,32GB,Branco,...,Osasco,Sao Paulo,Brazil,Computer,1536x864,Windows 7,Chrome 66.0,Noche,5,18

In [57]:
last_15 = last_15[last_15["event"] == "checkout"]

In [58]:
last_15 = last_15[last_15["month"] == 5]

In [59]:
last_15 = last_15[last_15["day"] >14]

In [60]:
last_15_product = last_15[["person","model"]]

In [61]:
last_15_product.head()

       person                             model
33   15ea8012            samsung galaxy s8 plus
60   43790d8f             motorola moto g4 plus
76   d614c608                 samsung galaxy j5
133  55d1e0ee  samsung galaxy core plus duos tv
147  bb78c182               motorola moto g3 4g

In [62]:
last_15_product = last_15_product.dropna()

In [63]:
last_15_product["marca"] = last_15_product["model"].map(lambda x:"apple" if(x.split(" ")[0] in ["iphone","ipad"]) else x.split(" ")[0])

In [64]:
last_15_product["version"] = last_15_product["model"].map(lambda x:" ".join(x.split(" ")[0:2]) if(x.split(" ")[0] in ["iphone","ipad"]) else " ".join(x.split(" ")[1:3]))

In [65]:
last_15_product.head()

       person                             model     marca      version
33   15ea8012            samsung galaxy s8 plus   samsung    galaxy s8
60   43790d8f             motorola moto g4 plus  motorola      moto g4
76   d614c608                 samsung galaxy j5   samsung    galaxy j5
133  55d1e0ee  samsung galaxy core plus duos tv   samsung  galaxy core
147  bb78c182               motorola moto g3 4g  motorola      moto g3

In [66]:
last_15_product = last_15_product.drop("model",axis=1)

In [67]:
"samsung" in prob_marcas.keys()

True

In [68]:
last_15_product["prob_marca"] = last_15_product["marca"].map(lambda x:prob_marcas[x] if(x in prob_marcas.keys()) else 0)

In [69]:
last_15_product["prob_model"] = last_15_product["version"].map(lambda x:prob_model[x] if(x in prob_model.keys()) else 0)

In [70]:
last_15_product.head()

       person     marca      version  prob_marca  prob_model
33   15ea8012   samsung    galaxy s8    0.426211         0.0
60   43790d8f  motorola      moto g4    0.129251         0.0
76   d614c608   samsung    galaxy j5    0.426211         0.0
133  55d1e0ee   samsung  galaxy core    0.426211         0.0
147  bb78c182  motorola      moto g3    0.129251         0.0

In [71]:
last_15_product = last_15_product[["person","prob_marca","prob_model"]]

In [72]:
last_15_product.head()

       person  prob_marca  prob_model
33   15ea8012    0.426211         0.0
60   43790d8f    0.129251         0.0
76   d614c608    0.426211         0.0
133  55d1e0ee    0.426211         0.0
147  bb78c182    0.129251         0.0

In [73]:
last_15_product["cant_conversiones"] = 1

In [74]:
last_15_product = last_15_product.groupby("person",as_index = False).sum()

In [75]:
last_15_product.head()

     person  prob_marca  prob_model  cant_conversiones
0  0008ed71    0.853541    0.017117                  3
1  00091926    0.819750    0.138314                  2
2  000ba417    2.260308    0.000000                  6
3  000c79fe    0.409875    0.026854                  1
4  000e4d9e    0.426211    0.000000                  1

In [76]:
last_15_product["prob_marca_en_base_checkout"] = last_15_product["prob_marca"] / (last_15_product["cant_conversiones"]+1)

In [77]:
last_15_product.head()

,person,prob_marca,prob_model,cant_conversiones,prob_marca_en_base_checkout
0,0008ed71,0.853541,0.017117,3,0.213385
1,00091926,0.819750,0.138314,2,0.273250
2,000ba417,2.260308,0.000000,6,0.322901
3,000c79fe,0.409875,0.026854,1,0.204938
4,000e4d9e,0.426211,0.000000,1,0.213106

In [78]:
last_15_product["prob_model_en_base_checkout"] = last_15_product["prob_model"] /(last_15_product["cant_conversiones"]+1)

In [79]:
last_15_product.head()

,person,prob_marca,prob_model,cant_conversiones,prob_marca_en_base_checkout,prob_model_en_base_checkout
0,0008ed71,0.853541,0.017117,3,0.213385,0.004279
1,00091926,0.819750,0.138314,2,0.273250,0.046105
2,000ba417,2.260308,0.000000,6,0.322901,0.000000
3,000c79fe,0.409875,0.026854,1,0.204938,0.013427
4,000e4d9e,0.426211,0.000000,1,0.213106,0.000000

In [81]:
last_15_product = last_15_product[["person","prob_marca_en_base_checkout","prob_model_en_base_checkout"]]

In [82]:
last_15_product.head()

     person  prob_marca_en_base_checkout  prob_model_en_base_checkout
0  0008ed71                     0.213385                     0.004279
1  00091926                     0.273250                     0.046105
2  000ba417                     0.322901                     0.000000
3  000c79fe                     0.204938                     0.013427
4  000e4d9e                     0.213106                     0.000000

In [83]:
usersDataTrain = pd.read_csv("setEntrenamiento.csv")

In [84]:
usersDataTrain.head()

,person,cant_seciones,event_checkout,event_conversion,event_ad campaign hit,event_lead,skus,Busca_terminos_populares,Computer,Smartphone,...,sku_multiple,count_activity_last_month,conversiones_lastmonth,checkout_lastmonth,viewed_lastmonth,label,kmean,prob_marca,prob_model,prob_marca_checkout
0,0008ed71,3,3.0,0.0,0.0,0.0,1,0,1.0,0.0,...,12.0,6.0,0.0,3.0,0.0,0,0,0.204731,0.002609,0.204731
1,000c79fe,1,1.0,0.0,1.0,0.0,1,8,0.0,1.0,...,79.0,17.0,0.0,1.0,3.0,0,0,0.229136,0.009815,0.229136
2,001802e4,1,1.0,0.0,5.0,0.0,1,0,0.0,1.0,...,24.0,19.0,0.0,1.0,4.0,0,0,0.250617,0.030126,0.250617
3,0019e639,21,15.0,2.0,29.0,0.0,1,3,1.0,0.0,...,608.0,359.0,1.0,6.0,161.0,0,2,0.200583,0.000000,0.200583
4,001b0bf9,1,2.0,1.0,0.0,0.0,1,0,0.0,0.0,...,24.0,7.0,1.0,2.0,2.0,0,3,0.424834,0.000000,0.424834

In [85]:
usersDataTrain = pd.merge(usersDataTrain,last_15_product,how = "left",on = "person")

In [86]:
usersDataTrain["prob_model_en_base_checkout"] = usersDataTrain["prob_model_en_base_checkout"].fillna(0)

In [87]:
usersDataTrain["prob_marca_en_base_checkout"] = usersDataTrain["prob_marca_en_base_checkout"].fillna(0)

In [89]:
usersDataTrain.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19414 entries, 0 to 19413
Data columns (total 79 columns):
person                               19414 non-null object
cant_seciones                        19414 non-null int64
event_checkout                       19414 non-null float64
event_conversion                     19414 non-null float64
event_ad campaign hit                19414 non-null float64
event_lead                           19414 non-null float64
skus                                 19414 non-null int64
Busca_terminos_populares             19414 non-null int64
Computer                             19414 non-null float64
Smartphone                           19414 non-null float64
otros                                19414 non-null float64
marca_apple                          19414 non-null float64
marca_asus                           19414 non-null float64
marca_lenovo                         19414 non-null float64
marca_lg                             19414 non-null float64
marca_motorola                       19414 non-null float64
marca_samsung                        19414 non-null float64
marca_sony                           19414 non-null float64
condition_Bom                        19414 non-null float64
condition_Bom - Sem Touch ID         19414 non-null float64
condition_Excelente                  19414 non-null float64
condition_Muito Bom                  19414 non-null float64
version_galaxy j7                    19414 non-null float64
version_galaxy j5                    19414 non-null float64
version_galaxy s7                    19414 non-null float64
version_iphone 6                     19414 non-null float64
version_iphone 5s                    19414 non-null float64
version_iphone 6s                    19414 non-null float64
version_moto g4                      19414 non-null float64
version_moto g2                      19414 non-null float64
version_galaxy s6                    19414 non-null float64
storage_128GB                        19414 non-null float64
storage_16GB                         19414 non-null float64
storage_256GB                        19414 non-null float64
storage_32GB                         19414 non-null float64
storage_4GB                          19414 non-null float64
storage_512MB                        19414 non-null float64
storage_64GB                         19414 non-null float64
storage_8GB                          19414 non-null float64
Parte del dia_Madrugada              19414 non-null float64
Parte del dia_Mañana                 19414 non-null float64
Parte del dia_Noche                  19414 non-null float64
Parte del dia_Tarde                  19414 non-null float64
campaign_source_google               19414 non-null float64
campaign_source_criteo               19414 non-null float64
campaign_source_rtbhouse             19414 non-null float64
channel_Direct                       19414 non-null float64
channel_Paid                         19414 non-null float64
channel_Organic                      19414 non-null float64
channel_Referral                     19414 non-null float64
Brasilero                            19414 non-null float64
ventas_region                        19414 non-null float64
count_activity                       19414 non-null float64
conversiones_15lastdays              19414 non-null float64
checkout_15lastdays                  19414 non-null float64
viewed_15lastday                     19414 non-null float64
color_Preto                          19414 non-null float64
color_Dourado                        19414 non-null float64
color_Branco                         19414 non-null float64
color_Cinza espacial                 19414 non-null float64
new_15lastdays                       19414 non-null float64
sku                                  19414 non-null float64
cantidad_De_Compras_De_Mismo_Sku     19414 non-null float64
Cantidad_De_Busquedas_Por_Termino    19414 non-null float64
search_and_purchase                  19414 non-null float64
cantidad_de_Url_de_compra            19414 non-null float64
cantidadDeStaticPage                 19414 non-null float64
sku_multiple                         19414 non-null float64
count_activity_last_month            19414 non-null float64
conversiones_lastmonth               19414 non-null float64
checkout_lastmonth                   19414 non-null float64
viewed_lastmonth                     19414 non-null float64
label                                19414 non-null int64
kmean                                19414 non-null int64
prob_marca                           19414 non-null float64
prob_model                           19414 non-null float64
prob_marca_checkout                  19414 non-null float64
prob_marca_en_base_checkout          19414 non-null float64
prob_model_en_base_checkout          19414 non-null float64
dtypes: float64(73), int64(5), object(1)
memory usage: 11.8+ MB

In [90]:
usersDataTrain.to_csv("setEntrenamiento.csv",index = False)

In [91]:
test = pd.read_csv('setTest.csv')

In [92]:
test.head()

,person,cant_seciones,event_checkout,event_conversion,event_ad campaign hit,event_lead,skus,Busca_terminos_populares,Computer,Smartphone,...,cantidadDeStaticPage,sku_multiple,count_activity_last_month,conversiones_lastmonth,checkout_lastmonth,viewed_lastmonth,kmean,prob_marca,prob_model,prob_marca_checkout
0,4886f805,1,1.0,0.0,0.0,0.0,1,0,0.0,1.0,...,0.0,21.0,9.0,0.0,1.0,4.0,0,0.424834,0.000000,0.000000
1,0297fc1e,96,7.0,0.0,29.0,1.0,1,5,0.0,1.0,...,0.0,326.0,312.0,0.0,2.0,233.0,0,0.283584,0.041827,0.041827
2,2d681dd8,2,1.0,0.0,1.0,0.0,1,1,1.0,0.0,...,0.0,53.0,26.0,0.0,1.0,13.0,0,0.197603,0.004908,0.004908
3,cccea85e,28,1.0,0.0,15.0,0.0,1,0,1.0,0.0,...,5.0,240.0,836.0,0.0,1.0,739.0,5,0.126065,0.000434,0.000434
4,4c8a8b93,20,2.0,0.0,14.0,0.0,1,9,0.0,1.0,...,0.0,132.0,257.0,0.0,2.0,177.0,0,0.288460,0.042187,0.042187

In [93]:
test = pd.merge(test,last_15_product,on="person",how="left")

In [94]:
test["prob_marca_en_base_checkout"] = test["prob_marca_en_base_checkout"].fillna(0)
test["prob_model_en_base_checkout"] = test["prob_model_en_base_checkout"].fillna(0)

In [95]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19415 entries, 0 to 19414
Data columns (total 78 columns):
person                               19415 non-null object
cant_seciones                        19415 non-null int64
event_checkout                       19415 non-null float64
event_conversion                     19415 non-null float64
event_ad campaign hit                19415 non-null float64
event_lead                           19415 non-null float64
skus                                 19415 non-null int64
Busca_terminos_populares             19415 non-null int64
Computer                             19415 non-null float64
Smartphone                           19415 non-null float64
otros                                19415 non-null float64
marca_apple                          19415 non-null float64
marca_asus                           19415 non-null float64
marca_lenovo                         19415 non-null float64
marca_lg                             19415 non-null float64
marca_motorola                       19415 non-null float64
marca_samsung                        19415 non-null float64
marca_sony                           19415 non-null float64
condition_Bom                        19415 non-null float64
condition_Bom - Sem Touch ID         19415 non-null float64
condition_Excelente                  19415 non-null float64
condition_Muito Bom                  19415 non-null float64
version_galaxy j7                    19415 non-null float64
version_galaxy j5                    19415 non-null float64
version_galaxy s7                    19415 non-null float64
version_iphone 6                     19415 non-null float64
version_iphone 5s                    19415 non-null float64
version_iphone 6s                    19415 non-null float64
version_moto g4                      19415 non-null float64
version_moto g2                      19415 non-null float64
version_galaxy s6                    19415 non-null float64
storage_128GB                        19415 non-null float64
storage_16GB                         19415 non-null float64
storage_256GB                        19415 non-null float64
storage_32GB                         19415 non-null float64
storage_4GB                          19415 non-null float64
storage_512MB                        19415 non-null float64
storage_64GB                         19415 non-null float64
storage_8GB                          19415 non-null float64
Parte del dia_Madrugada              19415 non-null float64
Parte del dia_Mañana                 19415 non-null float64
Parte del dia_Noche                  19415 non-null float64
Parte del dia_Tarde                  19415 non-null float64
campaign_source_google               19415 non-null float64
campaign_source_criteo               19415 non-null float64
campaign_source_rtbhouse             19415 non-null float64
channel_Direct                       19415 non-null float64
channel_Paid                         19415 non-null float64
channel_Organic                      19415 non-null float64
channel_Referral                     19415 non-null float64
Brasilero                            19415 non-null float64
ventas_region                        19415 non-null float64
count_activity                       19415 non-null float64
conversiones_15lastdays              19415 non-null float64
checkout_15lastdays                  19415 non-null float64
viewed_15lastday                     19415 non-null float64
color_Preto                          19415 non-null float64
color_Dourado                        19415 non-null float64
color_Branco                         19415 non-null float64
color_Cinza espacial                 19415 non-null float64
new_15lastdays                       19415 non-null float64
sku                                  19415 non-null float64
cantidad_De_Compras_De_Mismo_Sku     19415 non-null float64
Cantidad_De_Busquedas_Por_Termino    19415 non-null float64
search_and_purchase                  19415 non-null float64
cantidad_de_Url_de_compra            19415 non-null float64
cantidadDeStaticPage                 19415 non-null float64
sku_multiple                         19415 non-null float64
count_activity_last_month            19415 non-null float64
conversiones_lastmonth               19415 non-null float64
checkout_lastmonth                   19415 non-null float64
viewed_lastmonth                     19415 non-null float64
kmean                                19415 non-null int64
prob_marca                           19415 non-null float64
prob_model                           19415 non-null float64
prob_marca_checkout                  19415 non-null float64
prob_marca_en_base_checkout          19415 non-null float64
prob_model_en_base_checkout          19415 non-null float64
dtypes: float64(73), int64(4), object(1)
memory usage: 11.7+ MB

In [96]:
test.to_csv('setTest.csv',index = False)