In [1]:
import pandas as pd
import numpy as np
import datetime as dt

In [160]:
eventsData = pd.read_csv(r"C:\Users\brian\Documents\GitHub\TP2DATOS\Eventos(+completo).csv",low_memory = False)

In [161]:
eventosData = eventsData
eventosData = eventosData[['person','event']]
eventosData = pd.get_dummies(eventosData, columns=['event'])
eventosData = eventosData.groupby('person').agg({'event_ad campaign hit':'sum', 'event_brand listing':'sum',
       'event_checkout':'sum', 'event_conversion':'sum', 'event_generic listing':'sum',
       'event_lead':'sum', 'event_search engine hit':'sum', 'event_searched products':'sum',
       'event_staticpage':'sum', 'event_viewed product':'sum', 'event_visited site':'sum'})

In [162]:
eventosData.replace(0,np.nan,inplace = True)
eventosData[eventosData.columns].mean()

event_ad campaign hit       5.999624
event_brand listing        11.249259
event_checkout              1.989310
event_conversion            1.651759
event_generic listing       6.359976
event_lead                  1.697755
event_search engine hit     4.079828
event_searched products     9.976018
event_staticpage            2.762950
event_viewed product       33.614974
event_visited site          5.336253
dtype: float64

In [163]:
#Vamos a mapear si son mayores al promedio de la columna
eventosData['usuario_Checkeador'] = eventosData['event_checkout'].map(lambda x: 1 if (x >=  1.989310) else 0)
eventosData['usuario_susceptible_campaign'] = eventosData['event_ad campaign hit'].map(lambda x: 1 if (x >=  5.999624) else 0)
eventosData['usuario_buscador'] = eventosData['event_viewed product'].map(lambda x:1 if (x>= 33.614974) else 0)
eventosData['usuario_dubitativo']= ((eventosData['usuario_Checkeador'] + eventosData['usuario_buscador'] )== 2)
eventosData['usuario_poco_util'] =((eventosData['usuario_Checkeador'] + eventosData['usuario_buscador'] )== 2) 
eventosData = eventosData[['usuario_Checkeador','usuario_susceptible_campaign','usuario_buscador','usuario_dubitativo']]
eventosData = eventosData.fillna(0)

In [164]:
eventosData

,usuario_Checkeador,usuario_susceptible_campaign,usuario_buscador,usuario_dubitativo
person,,,,
0008ed71,1,0,0,False
00091926,1,1,1,True
00091a7a,0,0,0,False
000ba417,1,0,1,True
000c79fe,0,0,0,False
000e4d9e,0,1,1,False
000e619d,0,1,0,False
001001be,1,0,1,True
0010e89a,0,0,0,False
0016c4b5,0,0,0,False
001802e4,0,0,0,False
001804a2,1,0,0,False
0019e639,1,1,1,True
001a2273,0,0,0,False
001b0bf9,1,0,0,False
001ca5ee,0,1,1,False
001dfc31,0,0,0,False
001e9aea,1,1,0,False
0020152e,1,0,0,False
00202cdb,1,1,0,False
0022965d,1,1,0,False
0027574e,1,0,1,True
00295d74,1,0,0,False
002aea56,1,1,1,True
002b0188,0,0,0,False
002e74b2,0,0,0,False
002ed810,1,0,0,False
002fb981,0,1,0,False
00317e49,0,0,0,False
0031c75f,1,0,0,False
...,...,...,...,...
ffcaae19,0,0,0,False
ffcaeaae,0,0,0,False
ffccd5a1,1,0,0,False
ffcf952b,0,1,1,False
ffd41214,0,1,0,False
ffd62616,0,1,0,False
ffd9756a,0,0,0,False
ffda14ca,0,0,0,False
ffdafc72,1,0,0,False
ffddd0ec,0,0,0,False
ffde3628,1,0,1,True
ffe066cc,0,0,0,False
ffe53446,1,0,1,True
ffe7e848,1,1,1,True
ffeb80c5,0,0,0,False
ffebdbc9,0,0,0,False
ffecdf29,1,0,0,False
ffecea3d,0,0,0,False
ffed0342,1,1,1,True
ffed3d0e,0,0,0,False
ffee0f18,1,1,1,True
ffef83e6,0,0,1,False
fff1659c,1,1,0,False
fff1b11a,0,0,0,False
fff1caee,0,0,0,False
fff2bdde,1,0,1,True
fff54d61,0,0,0,False
fff72025,0,1,1,False
fff78145,1,0,0,False
fffd1246,0,0,0,False

In [165]:
eventsData["event"].value_counts()

viewed product       1248124
brand listing         216312
visited site          204069
ad campaign hit       191388
generic listing       160176
searched products     130616
search engine hit     106406
checkout               65315
staticpage             11201
conversion              7091
lead                     983
Name: event, dtype: int64

In [166]:
checkout = eventsData[eventsData["event"] == "checkout"]

In [167]:
compraPopular = checkout
compraPopular['compraPopular'] = 1
compraPopular['compraPopular'] = compraPopular['model'].map(lambda x: 1 if(('galaxy') in x or ('iphone') in x)else 0)
compraPopular = compraPopular.groupby('person').agg({'compraPopular':'first'})

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [168]:
popularSku = checkout
popularSku['sku'] = checkout["sku"].map(lambda x: x if ( x== 6371.0 or x== 2831.0 or x == 6357.0 or x == 3371.0) else 0)
popularSku['sku'].value_counts()
popularSku = pd.get_dummies(popularSku, columns = ['sku'])
popularSku = popularSku[['person','sku_0.0','sku_2831.0','sku_3371.0','sku_6357.0','sku_6371.0']]
popularSku = popularSku.groupby('person').agg({'sku_0.0': 'sum','sku_2831.0':'sum','sku_3371.0':'sum','sku_6357.0':'sum','sku_6371.0': 'sum'})
popularSku

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

          sku_0.0  sku_2831.0  sku_3371.0  sku_6357.0  sku_6371.0
person
0008ed71        3           0           0           0           0
00091926        2           0           0           0           0
000ba417        6           0           0           0           0
000c79fe        1           0           0           0           0
000e4d9e        1           0           0           0           0
000e619d        1           0           0           0           0
001001be        3           0           0           0           0
0010e89a        1           0           0           0           0
0016c4b5        1           0           0           0           0
001802e4        1           0           0           0           0
001804a2        1           1           0           0           0
0019e639       15           0           0           0           0
001a2273        1           0           0           0           0
001b0bf9        2           0           0           0           0
001ca5ee        1           0           0           0           0
001e9aea        3           0           0           0           0
0020152e        2           0           0           0           0
00202cdb        0           2           0           0           0
0022965d        8           0           0           0           0
0027574e        3           0           0           0           0
00295d74        2           0           0           0           0
002aea56       11           0           0           0           0
002b0188        1           0           0           0           0
002e74b2        1           0           0           0           0
002ed810        2           0           0           0           0
002fb981        1           0           0           0           0
00317e49        1           0           0           0           0
0031c75f        2           0           0           0           0
00344873        1           0           0           0           0
003847fc        2           0           0           0           0
...           ...         ...         ...         ...         ...
ffbb282f        0           0           0           0           1
ffbb90a9        1           0           0           0           0
ffbfc511        1           0           0           0           0
ffc0f2a0        4           0           0           0           0
ffc51f07        1           0           0           0           0
ffc670b3        7           0           0           0           0
ffcaae19        1           0           0           0           0
ffccd5a1        4           0           0           0           0
ffcf952b        1           0           0           0           0
ffd62616        1           0           0           0           0
ffd9756a        1           0           0           0           0
ffda14ca        1           0           0           0           0
ffdafc72        2           0           0           0           0
ffde3628        2           0           0           0           0
ffe066cc        1           0           0           0           0
ffe53446        4           0           0           0           1
ffe7e848        6           0           0           0           0
ffeb80c5        0           0           0           0           1
ffebdbc9        1           0           0           0           0
ffecdf29        3           0           0           0           0
ffed0342        7           0           0           0           0
ffed3d0e        1           0           0           0           0
ffee0f18        2           0           0           0           0
ffef83e6        1           0           0           0           0
fff1659c        3           0           0           0           0
fff1caee        1           0           0           0           0
fff2bdde        4           0           0           0           0
fff72025        1           0           0           0           0
fff78145        2           0           0           0           0
fffd1246        1           0           0           0           0

[32833 rows x 5 columns]

In [169]:
checkout.head()

,Unnamed: 0,timestamp,event,person,url,sku,model,condition,storage,color,...,new_vs_returning,city,region,country,device_type,screen_resolution,operating_system_version,browser_version,Parte del dia,compraPopular
33,33,2018-05-18 00:29:24,checkout,15ea8012,NaN,0.0,samsung galaxy s8 plus,Excelente,64GB,Prata,...,NaN,Itaquaquecetuba,Sao Paulo,Brazil,Smartphone,360x640,Android 7,Chrome Mobile 66.0,Noche,1
60,60,2018-05-18 00:22:58,checkout,43790d8f,NaN,0.0,motorola moto g4 plus,Bom,32GB,Bambu,...,NaN,São Paulo,Sao Paulo,Brazil,Smartphone,360x640,Android 6,Chrome Mobile 66.0,Noche,0
76,76,2018-05-18 00:38:51,checkout,d614c608,NaN,0.0,samsung galaxy j5,Bom,16GB,Branco,...,NaN,São José dos Campos,Sao Paulo,Brazil,Smartphone,360x640,Android 6.0.1,Chrome Mobile 66.0,Noche,1
133,133,2018-05-18 00:57:32,checkout,55d1e0ee,NaN,0.0,samsung galaxy core plus duos tv,Excelente,4GB,Preto,...,NaN,Florianópolis,Santa Catarina,Brazil,Smartphone,360x640,Android 6.0.1,Samsung Internet 6.4,Noche,1
147,147,2018-05-18 01:12:43,checkout,bb78c182,NaN,0.0,motorola moto g3 4g,Bom,16GB,Preto,...,NaN,Ceilandia,Federal District,Brazil,Computer,1920x1080,Windows 10,Chrome 66.0,Madrugada,0

In [170]:
checkout["marca"] = checkout["model"].map(lambda x:"apple" if(x.split(" ")[0] in ["iphone","ipad"]) else x.split(" ")[0])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [171]:
checkout["version"] = checkout["model"].map(lambda x:" ".join(x.split(" ")[0:2]) if(x.split(" ")[0] in ["iphone","ipad"]) else " ".join(x.split(" ")[1:3]))
checkout["version"].value_counts()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

iphone 6          6988
iphone 6s         5658
iphone 5s         5619
galaxy j5         4246
galaxy j7         3649
galaxy s7         3633
iphone 7          3621
galaxy s6         2921
galaxy s8         2350
moto g4           2035
moto g2           1802
galaxy a5         1657
galaxy s5         1363
galaxy gran       1336
iphone 5c         1223
moto g5           1198
iphone se         1118
moto g3            994
galaxy j2          937
galaxy note        877
galaxy a7          839
iphone 4s          816
iphone 5           804
galaxy j1          787
galaxy win         653
moto x             632
moto z             615
galaxy core        607
moto x2            466
iphone 4g          436
                  ...
ipad air            39
g4 h815p            37
g3 stylus           36
xperia z5           29
k4                  26
k8                  25
g3 beat             21
zenfone 2           20
 x                  19
g4 beat             19
g4 stylus           17
nexus 5             17
go 4g               16
ipad 3              15
zenfone 5           14
ipad 4              13
x power             13
ipad 2              12
you                 10
zenfone 6           10
gear s2              7
muv                  6
galaxy young         6
zenfone go           3
zenfone selfie       2
gear fit             2
l80 dual             1
muv pro              1
gear s3              1
galaxy mega          1
Name: version, Length: 92, dtype: int64

In [172]:
checkout.head()

,Unnamed: 0,timestamp,event,person,url,sku,model,condition,storage,color,...,region,country,device_type,screen_resolution,operating_system_version,browser_version,Parte del dia,compraPopular,marca,version
33,33,2018-05-18 00:29:24,checkout,15ea8012,NaN,0.0,samsung galaxy s8 plus,Excelente,64GB,Prata,...,Sao Paulo,Brazil,Smartphone,360x640,Android 7,Chrome Mobile 66.0,Noche,1,samsung,galaxy s8
60,60,2018-05-18 00:22:58,checkout,43790d8f,NaN,0.0,motorola moto g4 plus,Bom,32GB,Bambu,...,Sao Paulo,Brazil,Smartphone,360x640,Android 6,Chrome Mobile 66.0,Noche,0,motorola,moto g4
76,76,2018-05-18 00:38:51,checkout,d614c608,NaN,0.0,samsung galaxy j5,Bom,16GB,Branco,...,Sao Paulo,Brazil,Smartphone,360x640,Android 6.0.1,Chrome Mobile 66.0,Noche,1,samsung,galaxy j5
133,133,2018-05-18 00:57:32,checkout,55d1e0ee,NaN,0.0,samsung galaxy core plus duos tv,Excelente,4GB,Preto,...,Santa Catarina,Brazil,Smartphone,360x640,Android 6.0.1,Samsung Internet 6.4,Noche,1,samsung,galaxy core
147,147,2018-05-18 01:12:43,checkout,bb78c182,NaN,0.0,motorola moto g3 4g,Bom,16GB,Preto,...,Federal District,Brazil,Computer,1920x1080,Windows 10,Chrome 66.0,Madrugada,0,motorola,moto g3

In [173]:
checkout = checkout[["person","timestamp","marca","model"]]

In [174]:
checkout.head()

       person            timestamp     marca                             model
33   15ea8012  2018-05-18 00:29:24   samsung            samsung galaxy s8 plus
60   43790d8f  2018-05-18 00:22:58  motorola             motorola moto g4 plus
76   d614c608  2018-05-18 00:38:51   samsung                 samsung galaxy j5
133  55d1e0ee  2018-05-18 00:57:32   samsung  samsung galaxy core plus duos tv
147  bb78c182  2018-05-18 01:12:43  motorola               motorola moto g3 4g

In [175]:
marcas = checkout["marca"].value_counts()

In [176]:
marcas

samsung     27838
apple       26771
motorola     8442
lg           1140
lenovo        573
sony          416
asus          102
quantum        33
Name: marca, dtype: int64

In [177]:
prob_marcas = marcas/checkout["person"].count()

In [178]:
prob_marcas

samsung     0.426211
apple       0.409875
motorola    0.129251
lg          0.017454
lenovo      0.008773
sony        0.006369
asus        0.001562
quantum     0.000505
Name: marca, dtype: float64

In [179]:
modelos = checkout["model"].value_counts()

In [180]:
prob_model = modelos/checkout["person"].count()

In [181]:
prob_model.head()

iphone 6             0.086902
iphone 5s            0.086029
iphone 6s            0.069157
samsung galaxy j5    0.053433
samsung galaxy s7    0.031953
Name: model, dtype: float64

In [182]:
checkout.head()

       person            timestamp     marca                             model
33   15ea8012  2018-05-18 00:29:24   samsung            samsung galaxy s8 plus
60   43790d8f  2018-05-18 00:22:58  motorola             motorola moto g4 plus
76   d614c608  2018-05-18 00:38:51   samsung                 samsung galaxy j5
133  55d1e0ee  2018-05-18 00:57:32   samsung  samsung galaxy core plus duos tv
147  bb78c182  2018-05-18 01:12:43  motorola               motorola moto g3 4g

In [183]:
def datetime(date,format_string):
    return pd.to_datetime(date,format= format_string,errors='coerce')

eventsData["timestamp"]= datetime(eventsData["timestamp"],"%Y-%m-%dT%H:%M:%S")

In [184]:
eventsData["month"] = eventsData["timestamp"].map(lambda x: x.month)
eventsData["day"] = eventsData["timestamp"].map(lambda x: x.day)

In [185]:
eventsData.head()

,Unnamed: 0,timestamp,event,person,url,sku,model,condition,storage,color,...,city,region,country,device_type,screen_resolution,operating_system_version,browser_version,Parte del dia,month,day
0,0,2018-05-18 00:11:59,viewed product,4886f805,NaN,9288.0,samsung galaxy j7 prime,Excelente,32GB,Dourado,...,Cantagalo,Rio de Janeiro,Brazil,Smartphone,360x640,Android 7,Chrome Mobile 64.0,Noche,5,18
1,1,2018-05-18 00:11:27,viewed product,ad93850f,NaN,304.0,iphone 5s,Muito Bom,32GB,Cinza espacial,...,São Paulo,Sao Paulo,Brazil,Smartphone,360x640,Android 5.1.1,Chrome Mobile 66.0,Noche,5,18
2,2,2018-05-18 00:11:16,viewed product,0297fc1e,NaN,6888.0,iphone 6s,Muito Bom,64GB,Prateado,...,Niterói,Rio de Janeiro,Brazil,Smartphone,360x640,Android 6.0.1,Chrome Mobile 61.0,Noche,5,18
3,3,2018-05-18 00:11:14,viewed product,2d681dd8,NaN,11890.0,iphone 7,Bom,128GB,Vermelho,...,Juquitiba,Sao Paulo,Brazil,Computer,1360x768,Windows 8.1,Chrome 66.0,Noche,5,18
4,4,2018-05-18 00:11:09,viewed product,cccea85e,NaN,7517.0,lg g4 h818p,Excelente,32GB,Branco,...,Osasco,Sao Paulo,Brazil,Computer,1536x864,Windows 7,Chrome 66.0,Noche,5,18

In [186]:
last_15 = eventsData

In [187]:
last_15.head()

,Unnamed: 0,timestamp,event,person,url,sku,model,condition,storage,color,...,city,region,country,device_type,screen_resolution,operating_system_version,browser_version,Parte del dia,month,day
0,0,2018-05-18 00:11:59,viewed product,4886f805,NaN,9288.0,samsung galaxy j7 prime,Excelente,32GB,Dourado,...,Cantagalo,Rio de Janeiro,Brazil,Smartphone,360x640,Android 7,Chrome Mobile 64.0,Noche,5,18
1,1,2018-05-18 00:11:27,viewed product,ad93850f,NaN,304.0,iphone 5s,Muito Bom,32GB,Cinza espacial,...,São Paulo,Sao Paulo,Brazil,Smartphone,360x640,Android 5.1.1,Chrome Mobile 66.0,Noche,5,18
2,2,2018-05-18 00:11:16,viewed product,0297fc1e,NaN,6888.0,iphone 6s,Muito Bom,64GB,Prateado,...,Niterói,Rio de Janeiro,Brazil,Smartphone,360x640,Android 6.0.1,Chrome Mobile 61.0,Noche,5,18
3,3,2018-05-18 00:11:14,viewed product,2d681dd8,NaN,11890.0,iphone 7,Bom,128GB,Vermelho,...,Juquitiba,Sao Paulo,Brazil,Computer,1360x768,Windows 8.1,Chrome 66.0,Noche,5,18
4,4,2018-05-18 00:11:09,viewed product,cccea85e,NaN,7517.0,lg g4 h818p,Excelente,32GB,Branco,...,Osasco,Sao Paulo,Brazil,Computer,1536x864,Windows 7,Chrome 66.0,Noche,5,18

In [188]:
last_15 = last_15[last_15["event"] == "checkout"]

In [189]:
last_15 = last_15[last_15["month"] == 5]

In [190]:
last_15 = last_15[last_15["day"] >14]

In [191]:
last_15_product = last_15[["person","model"]]

In [192]:
last_15_product.head()

       person                             model
33   15ea8012            samsung galaxy s8 plus
60   43790d8f             motorola moto g4 plus
76   d614c608                 samsung galaxy j5
133  55d1e0ee  samsung galaxy core plus duos tv
147  bb78c182               motorola moto g3 4g

In [193]:
last_15_product = last_15_product.dropna()

In [194]:
last_15_product["marca"] = last_15_product["model"].map(lambda x:"apple" if(x.split(" ")[0] in ["iphone","ipad"]) else x.split(" ")[0])

In [195]:
last_15_product["version"] = last_15_product["model"].map(lambda x:" ".join(x.split(" ")[0:2]) if(x.split(" ")[0] in ["iphone","ipad"]) else " ".join(x.split(" ")[1:3]))

In [196]:
last_15_product.head()

       person                             model     marca      version
33   15ea8012            samsung galaxy s8 plus   samsung    galaxy s8
60   43790d8f             motorola moto g4 plus  motorola      moto g4
76   d614c608                 samsung galaxy j5   samsung    galaxy j5
133  55d1e0ee  samsung galaxy core plus duos tv   samsung  galaxy core
147  bb78c182               motorola moto g3 4g  motorola      moto g3

In [197]:
last_15_product = last_15_product.drop("model",axis=1)

In [198]:
"samsung" in prob_marcas.keys()

True

In [199]:
last_15_product["prob_marca"] = last_15_product["marca"].map(lambda x:prob_marcas[x] if(x in prob_marcas.keys()) else 0)

In [200]:
last_15_product["prob_model"] = last_15_product["version"].map(lambda x:prob_model[x] if(x in prob_model.keys()) else 0)

In [201]:
last_15_product.head()

       person     marca      version  prob_marca  prob_model
33   15ea8012   samsung    galaxy s8    0.426211         0.0
60   43790d8f  motorola      moto g4    0.129251         0.0
76   d614c608   samsung    galaxy j5    0.426211         0.0
133  55d1e0ee   samsung  galaxy core    0.426211         0.0
147  bb78c182  motorola      moto g3    0.129251         0.0

In [202]:
last_15_product = last_15_product[["person","prob_marca","prob_model"]]

In [203]:
last_15_product.head()

       person  prob_marca  prob_model
33   15ea8012    0.426211         0.0
60   43790d8f    0.129251         0.0
76   d614c608    0.426211         0.0
133  55d1e0ee    0.426211         0.0
147  bb78c182    0.129251         0.0

In [204]:
last_15_product["cant_conversiones"] = 1

In [205]:
last_15_product = last_15_product.groupby("person",as_index = False).sum()

In [206]:
last_15_product.head()

     person  prob_marca  prob_model  cant_conversiones
0  0008ed71    0.853541    0.017117                  3
1  00091926    0.819750    0.138314                  2
2  000ba417    2.260308    0.000000                  6
3  000c79fe    0.409875    0.026854                  1
4  000e4d9e    0.426211    0.000000                  1

In [207]:
last_15_product["prob_marca_en_base_checkout"] = last_15_product["prob_marca"] / (last_15_product["cant_conversiones"]+1)

In [208]:
last_15_product.head()

,person,prob_marca,prob_model,cant_conversiones,prob_marca_en_base_checkout
0,0008ed71,0.853541,0.017117,3,0.213385
1,00091926,0.819750,0.138314,2,0.273250
2,000ba417,2.260308,0.000000,6,0.322901
3,000c79fe,0.409875,0.026854,1,0.204938
4,000e4d9e,0.426211,0.000000,1,0.213106

In [209]:
last_15_product["prob_model_en_base_checkout"] = last_15_product["prob_model"] /(last_15_product["cant_conversiones"]+1)

In [210]:
last_15_product.head()

,person,prob_marca,prob_model,cant_conversiones,prob_marca_en_base_checkout,prob_model_en_base_checkout
0,0008ed71,0.853541,0.017117,3,0.213385,0.004279
1,00091926,0.819750,0.138314,2,0.273250,0.046105
2,000ba417,2.260308,0.000000,6,0.322901,0.000000
3,000c79fe,0.409875,0.026854,1,0.204938,0.013427
4,000e4d9e,0.426211,0.000000,1,0.213106,0.000000

In [211]:
last_15_product = last_15_product[["person","prob_marca_en_base_checkout","prob_model_en_base_checkout"]]

In [212]:
last_15_product.head()

     person  prob_marca_en_base_checkout  prob_model_en_base_checkout
0  0008ed71                     0.213385                     0.004279
1  00091926                     0.273250                     0.046105
2  000ba417                     0.322901                     0.000000
3  000c79fe                     0.204938                     0.013427
4  000e4d9e                     0.213106                     0.000000

In [235]:
usersDataTrain = pd.read_csv("setEntrenamiento.csv")

In [236]:
usersDataTrain = pd.merge(usersDataTrain,eventosData, how = 'left', on='person')
usersDataTrain = usersDataTrain.fillna(0)

In [237]:
usersDataTrain.head()

,Unnamed: 0,person,cant_seciones,event_checkout,event_conversion,event_ad campaign hit,event_lead,skus,screen_resolution,Busca_terminos_populares,...,Prob_sony,sku_multiple,label,prob_marca,prob_model,prob_marca_checkout,usuario_Checkeador,usuario_susceptible_campaign,usuario_buscador,usuario_dubitativo
0,0,0008ed71,3,3.0,0.0,0.0,0.0,1,0.0,0,...,0.0,12.0,0,0.204731,0.002609,0.204731,1,0,0,False
1,1,000c79fe,1,1.0,0.0,1.0,0.0,1,0.0,8,...,0.0,79.0,0,0.229136,0.009815,0.229136,0,0,0,False
2,2,001802e4,1,1.0,0.0,5.0,0.0,1,0.0,0,...,0.0,24.0,0,0.250617,0.030126,0.250617,0,0,0,False
3,3,0019e639,21,15.0,2.0,29.0,0.0,1,0.0,3,...,0.0,608.0,0,0.200583,0.000000,0.200583,1,1,1,True
4,4,001b0bf9,1,2.0,1.0,0.0,0.0,1,0.0,0,...,0.0,24.0,0,0.424834,0.000000,0.424834,1,0,0,False

In [238]:
usersDataTrain = pd.merge(usersDataTrain,last_15_product,how = "left",on = "person")

In [239]:
usersDataTrain = pd.merge(usersDataTrain,popularSku, how = 'left', on ='person')

In [240]:
usersDataTrain["prob_model_en_base_checkout"] = usersDataTrain["prob_model_en_base_checkout"].fillna(0)

In [241]:
usersDataTrain["prob_marca_en_base_checkout"] = usersDataTrain["prob_marca_en_base_checkout"].fillna(0)

In [242]:
usersDataTrain = pd.merge(usersDataTrain,compraPopular, how = 'left', on ='person')

In [243]:
usersDataTrain=usersDataTrain.fillna(0)
usersDataTrain.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19414 entries, 0 to 19413
Data columns (total 96 columns):
Unnamed: 0                           19414 non-null int64
person                               19414 non-null object
cant_seciones                        19414 non-null int64
event_checkout                       19414 non-null float64
event_conversion                     19414 non-null float64
event_ad campaign hit                19414 non-null float64
event_lead                           19414 non-null float64
skus                                 19414 non-null int64
screen_resolution                    19414 non-null float64
Busca_terminos_populares             19414 non-null int64
Computer                             19414 non-null float64
Smartphone                           19414 non-null float64
otros                                19414 non-null float64
marca_apple                          19414 non-null float64
marca_asus                           19414 non-null float64
marca_lenovo                         19414 non-null float64
marca_lg                             19414 non-null float64
marca_motorola                       19414 non-null float64
marca_samsung                        19414 non-null float64
marca_sony                           19414 non-null float64
condition_Bom                        19414 non-null float64
condition_Bom - Sem Touch ID         19414 non-null float64
condition_Excelente                  19414 non-null float64
condition_Muito Bom                  19414 non-null float64
version_galaxy j7                    19414 non-null float64
version_galaxy j5                    19414 non-null float64
version_galaxy s7                    19414 non-null float64
version_iphone 6                     19414 non-null float64
version_iphone 5s                    19414 non-null float64
version_iphone 6s                    19414 non-null float64
version_moto g4                      19414 non-null float64
version_moto g2                      19414 non-null float64
version_galaxy s6                    19414 non-null float64
storage_128GB                        19414 non-null float64
storage_16GB                         19414 non-null float64
storage_256GB                        19414 non-null float64
storage_32GB                         19414 non-null float64
storage_4GB                          19414 non-null float64
storage_512MB                        19414 non-null float64
storage_64GB                         19414 non-null float64
storage_8GB                          19414 non-null float64
Parte del dia_Madrugada              19414 non-null float64
Parte del dia_Mañana                 19414 non-null float64
Parte del dia_Noche                  19414 non-null float64
Parte del dia_Tarde                  19414 non-null float64
campaign_source_google               19414 non-null float64
campaign_source_criteo               19414 non-null float64
campaign_source_rtbhouse             19414 non-null float64
channel_Direct                       19414 non-null float64
channel_Paid                         19414 non-null float64
channel_Organic                      19414 non-null float64
channel_Referral                     19414 non-null float64
Brasilero                            19414 non-null float64
ventas_region                        19414 non-null float64
count_activity                       19414 non-null float64
conversiones_15lastdays              19414 non-null float64
checkout_15lastdays                  19414 non-null float64
viewed_15lastday                     19414 non-null float64
level_0                              19414 non-null float64
index                                19414 non-null float64
color_Preto                          19414 non-null float64
color_Dourado                        19414 non-null float64
color_Branco                         19414 non-null float64
color_Cinza espacial                 19414 non-null float64
new_15lastdays                       19414 non-null float64
sku                                  19414 non-null float64
cantidad_De_Compras_De_Mismo_Sku     19414 non-null float64
Cantidad_De_Busquedas_Por_Termino    19414 non-null float64
search_and_purchase                  19414 non-null float64
cantidad_de_Url_de_compra            19414 non-null float64
cantidadDeStaticPage                 19414 non-null float64
Prob_Apple                           19414 non-null float64
Prob_Asus                            19414 non-null float64
Prob_Lenovo                          19414 non-null float64
Prob_lg                              19414 non-null float64
Prob_motorola                        19414 non-null float64
Prob_quantum                         19414 non-null float64
Prob_samsung                         19414 non-null float64
Prob_sony                            19414 non-null float64
sku_multiple                         19414 non-null float64
label                                19414 non-null int64
prob_marca                           19414 non-null float64
prob_model                           19414 non-null float64
prob_marca_checkout                  19414 non-null float64
usuario_Checkeador                   19414 non-null int64
usuario_susceptible_campaign         19414 non-null int64
usuario_buscador                     19414 non-null int64
usuario_dubitativo                   19414 non-null bool
prob_marca_en_base_checkout          19414 non-null float64
prob_model_en_base_checkout          19414 non-null float64
sku_0.0                              19414 non-null float64
sku_2831.0                           19414 non-null float64
sku_3371.0                           19414 non-null float64
sku_6357.0                           19414 non-null float64
sku_6371.0                           19414 non-null float64
compraPopular                        19414 non-null float64
dtypes: bool(1), float64(86), int64(8), object(1)
memory usage: 14.2+ MB

In [244]:
usersDataTrain.to_csv("setEntrenamiento.csv",index = False)

In [245]:
test = pd.read_csv('setTest.csv')

In [246]:
test.head()

,Unnamed: 0,person,cant_seciones,event_checkout,event_conversion,event_ad campaign hit,event_lead,skus,screen_resolution,Busca_terminos_populares,...,Prob_Lenovo,Prob_lg,Prob_motorola,Prob_quantum,Prob_samsung,Prob_sony,sku_multiple,prob_marca,prob_model,prob_marca_checkout
0,0,4886f805,1,1.0,0.0,0.0,0.0,1,0.0,0,...,0.0,0.0,0.000000,0.0,0.426211,0.0,21.0,0.424834,0.000000,0.000000
1,1,0297fc1e,96,7.0,0.0,29.0,1.0,1,0.0,5,...,0.0,0.0,0.000000,0.0,0.000000,0.0,326.0,0.283584,0.041827,0.041827
2,2,2d681dd8,2,1.0,0.0,1.0,0.0,1,0.0,1,...,0.0,0.0,0.129251,0.0,0.000000,0.0,53.0,0.197603,0.004908,0.004908
3,3,cccea85e,28,1.0,0.0,15.0,0.0,1,0.0,0,...,0.0,0.0,0.129251,0.0,0.000000,0.0,240.0,0.126065,0.000434,0.000434
4,4,4c8a8b93,20,2.0,0.0,14.0,0.0,1,0.0,9,...,0.0,0.0,0.000000,0.0,0.000000,0.0,132.0,0.288460,0.042187,0.042187

In [247]:
test = pd.merge(test,last_15_product,on="person",how="left")
test = pd.merge(test,popularSku, on ='person', how='left')
test = pd.merge(test,compraPopular, how = 'left', on ='person')

In [248]:
test = pd.merge(test,eventosData, how = 'left', on='person')
test = test.fillna(0)

In [249]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19415 entries, 0 to 19414
Data columns (total 95 columns):
Unnamed: 0                           19415 non-null int64
person                               19415 non-null object
cant_seciones                        19415 non-null int64
event_checkout                       19415 non-null float64
event_conversion                     19415 non-null float64
event_ad campaign hit                19415 non-null float64
event_lead                           19415 non-null float64
skus                                 19415 non-null int64
screen_resolution                    19415 non-null float64
Busca_terminos_populares             19415 non-null int64
Computer                             19415 non-null float64
Smartphone                           19415 non-null float64
otros                                19415 non-null float64
marca_apple                          19415 non-null float64
marca_asus                           19415 non-null float64
marca_lenovo                         19415 non-null float64
marca_lg                             19415 non-null float64
marca_motorola                       19415 non-null float64
marca_samsung                        19415 non-null float64
marca_sony                           19415 non-null float64
condition_Bom                        19415 non-null float64
condition_Bom - Sem Touch ID         19415 non-null float64
condition_Excelente                  19415 non-null float64
condition_Muito Bom                  19415 non-null float64
version_galaxy j7                    19415 non-null float64
version_galaxy j5                    19415 non-null float64
version_galaxy s7                    19415 non-null float64
version_iphone 6                     19415 non-null float64
version_iphone 5s                    19415 non-null float64
version_iphone 6s                    19415 non-null float64
version_moto g4                      19415 non-null float64
version_moto g2                      19415 non-null float64
version_galaxy s6                    19415 non-null float64
storage_128GB                        19415 non-null float64
storage_16GB                         19415 non-null float64
storage_256GB                        19415 non-null float64
storage_32GB                         19415 non-null float64
storage_4GB                          19415 non-null float64
storage_512MB                        19415 non-null float64
storage_64GB                         19415 non-null float64
storage_8GB                          19415 non-null float64
Parte del dia_Madrugada              19415 non-null float64
Parte del dia_Mañana                 19415 non-null float64
Parte del dia_Noche                  19415 non-null float64
Parte del dia_Tarde                  19415 non-null float64
campaign_source_google               19415 non-null float64
campaign_source_criteo               19415 non-null float64
campaign_source_rtbhouse             19415 non-null float64
channel_Direct                       19415 non-null float64
channel_Paid                         19415 non-null float64
channel_Organic                      19415 non-null float64
channel_Referral                     19415 non-null float64
Brasilero                            19415 non-null float64
ventas_region                        19415 non-null float64
count_activity                       19415 non-null float64
conversiones_15lastdays              19415 non-null float64
checkout_15lastdays                  19415 non-null float64
viewed_15lastday                     19415 non-null float64
level_0                              19415 non-null float64
index                                19415 non-null float64
color_Preto                          19415 non-null float64
color_Dourado                        19415 non-null float64
color_Branco                         19415 non-null float64
color_Cinza espacial                 19415 non-null float64
new_15lastdays                       19415 non-null float64
sku                                  19415 non-null float64
cantidad_De_Compras_De_Mismo_Sku     19415 non-null float64
Cantidad_De_Busquedas_Por_Termino    19415 non-null float64
search_and_purchase                  19415 non-null float64
cantidad_de_Url_de_compra            19415 non-null float64
cantidadDeStaticPage                 19415 non-null float64
Prob_Apple                           19415 non-null float64
Prob_Asus                            19415 non-null float64
Prob_Lenovo                          19415 non-null float64
Prob_lg                              19415 non-null float64
Prob_motorola                        19415 non-null float64
Prob_quantum                         19415 non-null float64
Prob_samsung                         19415 non-null float64
Prob_sony                            19415 non-null float64
sku_multiple                         19415 non-null float64
prob_marca                           19415 non-null float64
prob_model                           19415 non-null float64
prob_marca_checkout                  19415 non-null float64
prob_marca_en_base_checkout          19415 non-null float64
prob_model_en_base_checkout          19415 non-null float64
sku_0.0                              19415 non-null float64
sku_2831.0                           19415 non-null float64
sku_3371.0                           19415 non-null float64
sku_6357.0                           19415 non-null float64
sku_6371.0                           19415 non-null float64
compraPopular                        19415 non-null float64
usuario_Checkeador                   19415 non-null int64
usuario_susceptible_campaign         19415 non-null int64
usuario_buscador                     19415 non-null int64
usuario_dubitativo                   19415 non-null bool
dtypes: bool(1), float64(86), int64(7), object(1)
memory usage: 14.1+ MB

In [250]:
test.to_csv('setTest.csv',index = False)